// constants/UsefulMaterials/Architecture/earlyModernData.ts

import type { ArchitecturalSite } from './ancientMedievalData';

export const EARLY_MODERN_COLUMNS = [
  { 
    header: 'Зображення', 
    accessor: (row: ArchitecturalSite) => {
      if (!row.imageUrl) return '';
      return {
        type: 'image',
        src: row.imageUrl,
        alt: row.name_location,
        style: 'max-height:100px; max-width:120px; object-fit:contain;'
      };
    }, 
    width: 25 
  },
  { header: 'Назва та місце', accessor: 'name_location', width: 25 },
  { header: 'Стиль', accessor: 'style', width: 12 },
  { header: 'Опис', accessor: (row: ArchitecturalSite) => `📅 ${row.yearBuilt} | ${row.description}`, width: 'auto' },
] as const;

export const EARLY_MODERN_SHOW_ROW_NUMBERS = true;

export const earlyModernData: ArchitecturalSite[] = [
  {
    id: 1,
    name_location: "Острозький замок: Кругла (Нова) вежа (Острог)",
    yearBuilt: "кінець XVI ст.",
    style: "Ренесанс, готика",
    description: "Велике князівство Литовське, Річ Посполита | Оборонна вежа, збудована князями Острозькими. Символ могутності родини, меценатів освіти та культури.",
    imageUrl: "/images/architecture/earlyModern/001.webp",
  },
  {
    id: 2,
    name_location: "Чорна Кам'яниця (Львів)",
    yearBuilt: "кінець XVI ст.",
    style: "Ренесанс",
    description: "Річ Посполита | Пам'ятка ренесансної архітектури Львова. Фасад облицьований пісковиком, прикрашений скульптурними зображеннями.",
    imageUrl: "/images/architecture/earlyModern/002.webp",
  },
  {
    id: 3,
    name_location: "Будинок Корнякта (Львів)",
    yearBuilt: "1580 р.",
    style: "Ренесанс",
    description: "Річ Посполита | Палац грецького купця Костянтина Корнякта. Видатна пам'ятка ренесансу, частина історичного ансамблю площі Ринок.",
    imageUrl: "/images/architecture/earlyModern/003.webp",
  },
  {
    id: 4,
    name_location: "Церква Зішестя Святого Духа (с. Потелич)",
    yearBuilt: "1502 р.",
    style: "Готика, ренесанс",
    description: "Річ Посполита | Одна з найстаріших дерев'яних церков Галичини, пам'ятка готичної архітектури.",
    imageUrl: "/images/architecture/earlyModern/004.webp",
  },
  {
    id: 5,
    name_location: "Бахчисарайський історико-культурний заповідник (Бахчисарай)",
    yearBuilt: "XVI–XVIII ст.",
    style: "Османська архітектура, кримсько-татарський стиль",
    description: "Кримське ханство | Колишня резиденція кримських ханів. Поєднання османських, перських та європейських архітектурних традицій.",
    imageUrl: "/images/architecture/earlyModern/005.webp",
  },
  {
    id: 6,
    name_location: "Меджибізький замок (Меджибіж)",
    yearBuilt: "XVI ст.",
    style: "Ренесанс, готика",
    description: "Річ Посполита | Фортеця, відома як місце полону Богдана Хмельницького. Оборонна архітектура з палацом князів Острозьких.",
    imageUrl: "/images/architecture/earlyModern/006.webp",
  },
  {
    id: 7,
    name_location: "Церква Успіння (Львів)",
    yearBuilt: "1591–1629 рр.",
    style: "Ренесанс",
    description: "Річ Посполита | Головний храм Львівського Успенського братства, символ українського православ'я. Спілка архітекторів з Італії.",
    imageUrl: "/images/architecture/earlyModern/007.webp",
  },
  {
    id: 8,
    name_location: "Вежа Корнякта (Львів)",
    yearBuilt: "1572–1578 рр.",
    style: "Ренесанс",
    description: "Річ Посполита | Оборонна вежа, яка входила до міських укріплень Львова. Символ могутності купця Костянтина Корнякта.",
    imageUrl: "/images/architecture/earlyModern/008.webp",
  },
  {
    id: 9,
    name_location: "Каплиця Трьох Святителів (Львів)",
    yearBuilt: "1578 - 1591 рр.",
    style: "Ренесанс",
    description: "Річ Посполита | Будівля є частиною єдиного комплекса, який складається з Успенської церкви та вежі Корнякта і примикає стінами до них. ",
    imageUrl: "/images/architecture/earlyModern/009.webp",
  },
  {
    id: 10,
    name_location: "Латинський катедральний собор (Львів)",
    yearBuilt: "XV–XVI ст.",
    style: "Готика, ренесанс, бароко",
    description: "Річ Посполита | Головний католицький храм Львова. Поєднання готики, ренесансу та бароко. Всередині каплиця Боїмів.",
    imageUrl: "/images/architecture/earlyModern/010.webp",
  },
  {
    id: 11,
    name_location: "Каплиця Боїмів (Львів)",
    yearBuilt: "1609–1617 рр.",
    style: "Ренесанс, маньєризм",
    description: "Річ Посполита | Шедевр ренесансної скульптури. Родинна усипальниця родини Боїмів. Зведена як усипальня родини купців Боїмів, вона відома унікальним різьбленим фасадом. Зараз це музей, філія Львівської національної галереї мистецтв.",
    imageUrl: "/images/architecture/earlyModern/011.webp",
  },
  {
    id: 12,
    name_location: "Підгорецький замок (с. Підгірці, Львівська область)",
    yearBuilt: "1635–1640 рр.",
    style: "Ренесанс, бароко",
    description: "Річ Посполита | Палацово-замковий комплекс. Поєднання оборонної архітектури та ренесансного палацу з барочним декором.",
    imageUrl: "/images/architecture/earlyModern/012.webp",
  },
  {
    id: 13,
    name_location: "Іллінська церква (с. Суботів, Черкаська область)",
    yearBuilt: "1656 р.",
    style: "Українське бароко",
    description: "Гетьманщина | Усипальниця Богдана Хмельницького. Пам'ятка українського бароко, мурована п'ятибанна церква.",
    imageUrl: "/images/architecture/earlyModern/013.webp",
  },
  {
    id: 14,
    name_location: "Монастир та костел кармеліток босих (Львів)",
    yearBuilt: "др. половина XVII ст.",
    style: "Бароко",
    description: "Річ Посполита | Архітектурний комплекс у стилі бароко. Виразний фасад з вежами.",
    imageUrl: "/images/architecture/earlyModern/014.webp",
  },
  {
    id: 15,
    name_location: "Троїцький собор Троїцько-Іллінського монастиря (Чернігів)",
    yearBuilt: "1679–1689 рр.",
    style: "Українське бароко",
    description: "Гетьманщина | Пам'ятка українського бароко. Трибанна церква з виразним декором.",
    imageUrl: "/images/architecture/earlyModern/015.webp",
  },
  {
    id: 16,
    name_location: "Покровський собор (Харків)",
    yearBuilt: "1689 р.",
    style: "Українське бароко",
    description: "Гетьманщина | Оборонний храм-фортеця. Пам'ятка українського бароко, зразок козацької архітектури.",
    imageUrl: "/images/architecture/earlyModern/016.webp",
  },
  {
    id: 17,
    name_location: "Оборонна синагога (Жовква, Львівська обл.)",
    yearBuilt: "1692–1698 рр.",
    style: "Ренесанс, оборонна архітектура",
    description: "Річ Посполита | Унікальна пам'ятка оборонної сакральної архітектури. Синагога-фортеця.",
    imageUrl: "/images/architecture/earlyModern/017.webp",
  },
  {
    id: 18,
    name_location: "Георгіївська церква Видубицького монастиря (Київ)",
    yearBuilt: "1696–1701 рр.",
    style: "Українське бароко",
    description: "Гетьманщина | Шестибанна церква, прикрашена ліпленням. Вид на Дніпро.",
    imageUrl: "/images/architecture/earlyModern/018.webp",
  },
  {
    id: 19,
    name_location: "Преображенська церква (с. Великі Сорочинці, Полтавська обл.)",
    yearBuilt: "1732 р.",
    style: "Українське бароко",
    description: "Гетьманщина | Відома завдяки ярмарку та опису Миколи Гоголя. Пам'ятка бароко.",
    imageUrl: "/images/architecture/earlyModern/019.webp",
  },
  {
    id: 20,
    name_location: "Домініканський собор (Храм Пресвятої Євхаристії) (Львів)",
    yearBuilt: "1749–1764 рр.",
    style: "Бароко",
    description: "Річ Посполита | Шедевр барочної архітектури. Величезний купол, багата ліпнина.",
    imageUrl: "/images/architecture/earlyModern/020.webp",
  },
  {
    id: 21,
    name_location: "Ансамбль площі Ринок (Жовква, Львівська обл.)",
    yearBuilt: "XVI–XVII ст.",
    style: "Ренесанс",
    description: "Річ Посполита | Зразок ренесансної містобудівної композиції. Аркади та кам'яниці навколо площі.",
    imageUrl: "/images/architecture/earlyModern/021.webp",
  },
  {
    id: 22,
    name_location: "Собор святого Юра (Львів)",
    yearBuilt: "1744–1762 рр.",
    style: "Бароко, рококо",
    description: "Річ Посполита | Головний храм Української греко-католицької церкви. Шедевр бароко, пам'ятка ЮНЕСКО.",
    imageUrl: "/images/architecture/earlyModern/022.webp",
  },
  {
    id: 23,
    name_location: "Скульптурна група святого Юрія змієборця на фасаді собору святого Юра (Львів)",
    yearBuilt: "1744–1762 рр.",
    style: "Бароко, рококо",
    description: "Річ Посполита | Видатний зразок барокової скульптури. Динамічна композиція зі святим Георгієм.",
    imageUrl: "/images/architecture/earlyModern/023.webp",
  },
  {
    id: 24,
    name_location: "Андріївська церква (Київ)",
    yearBuilt: "1747–1757 рр.",
    style: "Українське бароко",
    description: "Російська імперія | Шедевр архітектури, спроектований Бартоломео Растреллі. П'ятибанна церква на Старокиївській горі.",
    imageUrl: "/images/architecture/earlyModern/024.webp",
  },
  {
    id: 25,
    name_location: "Ратуша (Бучач)",
    yearBuilt: "1751 р.",
    style: "Бароко",
    description: "Річ Посполита | Вежа-ратуша зі скульптурами. Пам'ятка барокової архітектури.",
    imageUrl: "/images/architecture/earlyModern/025.webp",
  },
  {
    id: 26,
    name_location: "Покровська церква (Київ)",
    yearBuilt: "1766 р.",
    style: "Українське бароко",
    description: "Гетьманщина | Пам'ятка архітектури, яку іноді приписують Івану Григоровичу-Барському. Храм у стилі українського бароко.",
    imageUrl: "/images/architecture/earlyModern/026.webp",
  },
  {
    id: 27,
    name_location: "Троїцький собор (Новомосковськ)",
    yearBuilt: "1775–1780 рр.",
    style: "Українське бароко",
    description: "Гетьманщина | Дев'ятибанний дерев'яний собор, побудований без жодного цвяха. Шедевр народної архітектури.",
    imageUrl: "/images/architecture/earlyModern/027.webp",
  },
  {
    id: 28,
    name_location: "Успенський собор Почаївської лаври (Почаїв)",
    yearBuilt: "1771–1783 рр.",
    style: "Бароко, класицизм",
    description: "Річ Посполита, Російська імперія | Головний храм Почаївської лаври. Поєднання барокових та класицистичних форм.",
    imageUrl: "/images/architecture/earlyModern/028.webp",
  },
  {
    id: 29,
    name_location: "Колишній Губернаторський палац - згодом перший корпус Харківського університету (Харків)",
    yearBuilt: "1766–1777 рр.",
    style: "Пізнє бароко з елементами раннього класицизму",
    description: "Російська імперія | Будівля є рідкісним зразком перехідного стилю від бароко до раннього класицизму. Спочатку палац призначався для урочистих прийомів імператорських осіб, проте у 1805 році його передали новоствореному Харківському університету.",
    imageUrl: "/images/architecture/earlyModern/029.webp",
  },
  {
    id: 30,
    name_location: "Палац Кирила Розумовського (Батурин, Чернігівська обл.)",
    yearBuilt: "1799–1803 рр.",
    style: "Класицизм",
    description: "Російська імперія | Палац останнього гетьмана України. Зразок класицизму з розкішним інтер'єром.",
    imageUrl: "/images/architecture/earlyModern/030.webp",
  },
];