import type { Artwork } from './artTypes';

export const KYIVAN_RUS_ART_COLUMNS = [
  { header: 'Зображення', accessor: 'imageUrl', width: 25 },
  { header: 'Назва та автор', accessor: (row: Artwork) => `${row.title} (${row.author})`, width: 35 },
  { header: 'Дата', accessor: 'date', width: 15 },
  { header: 'Опис / Стиль', accessor: (row: Artwork) => `${row.style} | ${row.description}`, width: 'auto' },
] as const;

export const KYIVAN_RUS_ART_SHOW_ROW_NUMBERS = true;

export const kyivanRusArtData: Artwork[] = [
  {
    id: 1,
    imageUrl: "/images/art/kyivanRus/201_Pochid_Olega_na_Cargorod.webp",
    title: "Похід Олега на Царгород",
    author: "Мініатюра «Повісті минулих літ»",
    date: "XV ст. (список), подія 907 р.",
    style: "Книжкова мініатюра",
    description: "Ілюстрація успішного походу князя Олега на Константинополь (907 р.), який завершився укладенням вигідного торговельного договору Русі з Візантією.",
  },
  {
    id: 2,
    imageUrl: "/images/art/kyivanRus/202_Pomsta_Olgi.webp",
    title: "Помста княгині Ольги древлянам",
    author: "Мініатюра «Повісті минулих літ»",
    date: "XV ст. (список), подія 945 р.",
    style: "Книжкова мініатюра",
    description: "Ілюстрація спалення древлянського міста Іскоростень (945 р.), що відбулося після вбивства князя Ігоря. Частина циклу про помсту Ольги.",
  },
  {
    id: 3,
    imageUrl: "/images/art/kyivanRus/203_Chreszczennja_Olgi_v_Kornstantynopole.webp",
    title: "Хрещення княгині Ольги в Константинополі",
    author: "Мініатюра «Повісті минулих літ»",
    date: "XV ст. (список), подія 957 р.",
    style: "Книжкова мініатюра",
    description: "Ілюстрація прийняття християнства княгинею Ольгою в Константинополі. Перша руська правителька, яка офіційно прийняла християнство.",
  },
  {
    id: 4,
    imageUrl: "/images/art/kyivanRus/204_Chreszczennja_Wolodymyra_v_Korsuni.webp",
    title: "Хрещення князя Володимира Святославича у Корсуні (Херсонесі)",
    author: "Мініатюра «Повісті временних літ»",
    date: "XV ст. (список), подія 988 р.",
    style: "Книжкова мініатюра",
    description: "Ілюстрація хрещення князя Володимира у Корсуні (Херсонесі) у 988 році. Символічне зображення вибору віри та хрещення Русі.",
  },
  {
    id: 5,
    imageUrl: "/images/art/kyivanRus/205_Wyszgorodskaya_ikona_Bogomateri.webp",
    title: "Вишгородська ікона Богородиці",
    author: "Невідомий майстер (візантійсько-руська школа)",
    date: "XII ст.",
    style: "Іконопис",
    description: "Давньоруська ікона, яка зберігалася у Вишгороді. Пізніше була вивезена до Росії, де отримала назву Володимирська ікона Божої Матері. Один із найшанованіших образів.",
  },
  {
    id: 6,
    imageUrl: "/images/art/kyivanRus/206_Swenska_ikona_Bogomateri.webp",
    title: "Свенська ікона Богородиці з Антонієм і Феодосієм Печерськими",
    author: "Києво-Печерська іконописна школа",
    date: "XII ст.",
    style: "Іконопис",
    description: "Унікальна ікона, на якій Богородиця зображена з преподобними Антонієм та Феодосієм Печерськими – засновниками Києво-Печерської лаври.",
  },
  {
    id: 7,
    imageUrl: "/images/art/kyivanRus/207_Mozaika_Bogomateri_Oranty.webp",
    title: "Мозаїка Богоматері Оранти",
    author: "Візантійські майстри",
    date: "перша половина XI ст.",
    style: "Монументальне мистецтво (мозаїка)",
    description: "Головний образ Софійського собору в Києві. Оранта (Моляща) – символ заступництва, «Нерушима Стіна». Зображена в центральній апсиді.",
  },
  {
    id: 8,
    imageUrl: "/images/art/kyivanRus/208_Mozaika_Christa.webp",
    title: "Мозаїка Христа Вседержителя (Пантократора)",
    author: "Візантійські майстри",
    date: "перша половина XI ст.",
    style: "Монументальне мистецтво (мозаїка)",
    description: "Розташована в куполі Софійського собору. Образ Всевладного Судді, який панує над світом. Урочистість і велич візантійської традиції.",
  },
  {
    id: 9,
    imageUrl: "/images/art/kyivanRus/209_Ewangelist_Luka_Ostr_Ewangelie.webp",
    title: "Євангеліст Лука",
    author: "Остромирове Євангеліє",
    date: "1056–1057 рр.",
    style: "Книжкова мініатюра",
    description: "Мініатюра з найдавнішої датованої рукописної книги Київської Русі. Зразок впливу візантійської традиції в давньоруському книжковому мистецтві.",
  },
  {
    id: 10,
    imageUrl: "/images/art/kyivanRus/210_Rodyna_Yaroslawicziw.webp",
    title: "Родина князя Святослава Ярославича",
    author: "Мініатюра «Ізборника»",
    date: "1073 р.",
    style: "Книжкова мініатюра",
    description: "Одна з перших світських мініатюр. Зображення князя Святослава Ярославича з родиною. Важливе джерело з історії костюма та уявлень про владу.",
  },
  {
    id: 11,
    imageUrl: "/images/art/kyivanRus/211_Cholmska_ikona_Bogomateri.webp",
    title: "Холмська ікона Богородиці",
    author: "Галицько-волинська школа",
    date: "XII ст.",
    style: "Іконопис",
    description: "Пам'ятка галицько-волинської школи іконопису. Вважалася чудотворною і була пов'язана з історією міста Холм, столиці Данила Галицького.",
  },
  {
    id: 12,
    imageUrl: "/images/art/kyivanRus/212_Dorogobuzska_ikona_Bogomateri.webp",
    title: "Дорогобузька ікона Богородиці",
    author: "Волинська школа",
    date: "остання третина XIII ст.",
    style: "Іконопис",
    description: "Зразок волинського іконопису після монгольської навали. Свідчення збереження традицій давньоруського мистецтва в складний період історії.",
  },
];