import type { Artwork } from './artTypes';

export const MODERN_ART_COLUMNS = [
  { header: 'Зображення', accessor: 'imageUrl', width: 25 },
  { header: 'Назва та автор', accessor: (row: Artwork) => `${row.title} (${row.author})`, width: 35 },
  { header: 'Дата', accessor: 'date', width: 15 },
  { header: 'Опис / Стиль', accessor: (row: Artwork) => `${row.style} | ${row.description}`, width: 'auto' },
] as const;

export const MODERN_ART_SHOW_ROW_NUMBERS = true;

export const modernArtData: Artwork[] = [
  {
    id: 1,
    imageUrl: "/images/art/modern/401_Kateryna_II_Borowikowsky.webp",
    title: "Катерина II на прогулянці в Царськосельскому парку",
    author: "Володимир Боровиковський",
    date: "1794 р.",
    style: "Сентименталізм",
    description: "Імператриця зображена як звичайна поміщиця на тлі парку, без атрибутів влади. Зразок сентименталізму – увага до почуттів, «природної» людини.",
  },
  {
    id: 2,
    imageUrl: "/images/art/modern/402_Diwczyna_z_Podillja_Tropinin.webp",
    title: "Дівчина з Поділля",
    author: "Василь Тропінін",
    date: "1820-ті рр.",
    style: "Сентименталізм / Романтизм",
    description: "З циклу «Українські типи». Увага до національного типажу («українка»). Ідеалізований, але живий образ дівчини в народному вбранні.",
  },
  {
    id: 3,
    imageUrl: "/images/art/modern/403_Diwczyna_z_Podillja_2_Tropinin.webp",
    title: "Дівчина зі сливами",
    author: "Василь Тропінін",
    date: "1820-ті рр.",
    style: "Сентименталізм / Романтизм",
    description: "З циклу «Українські типи». Романтизація селянського побуту. Жіночі образи в українському вбранні, підкреслення зв'язку людини з природою.",
  },
  {
    id: 4,
    imageUrl: "/images/art/modern/404_Diwczyna_z_Malorossiyi_Tropinin.webp",
    title: "Дівчина-українка у пейзажі",
    author: "Василь Тропінін",
    date: "1821 р.",
    style: "Сентименталізм / Романтизм",
    description: "З циклу «Українські типи». Пробудження інтересу до повсякденного життя та культури людини з народу. Поєднання портрета та пейзажу.",
  },
  {
    id: 5,
    imageUrl: "/images/art/modern/405_Szewczenko_awtoportret.webp",
    title: "Автопортрет",
    author: "Тарас Шевченко",
    date: "1840 р.",
    style: "Романтизм / Академізм",
    description: "Багаторазово копіювався та тиражувався. Став «візитівкою» митця, символом української культури. Поєднання романтичного пафосу з академічною технікою.",
  },
  {
    id: 6,
    imageUrl: "/images/art/modern/406_Shewczenko_Kateryna.webp",
    title: "Катерина",
    author: "Тарас Шевченко",
    date: "1842 р.",
    style: "Романтизм / Критичний реалізм",
    description: "Ілюстрація до власної поеми («жіноча доля»). Трагедія зведеної дівчини, соціальна нерівність. Один із ранніх зразків критичного реалізму в українському мистецтві.",
  },
  {
    id: 7,
    imageUrl: "/images/art/modern/407_Shewczenko_Oforty.webp",
    title: "Офорти з серії «Живописна Україна»",
    author: "Тарас Шевченко",
    date: "1844 р.",
    style: "Графіка (офорт), романтизм, реалізм",
    description: "Перші спроби відтворити історичне минуле та побут України. Вплинули на розвиток української історичної тематики в мистецтві.",
  },
  {
    id: 8,
    imageUrl: "/images/art/modern/408_Sadyba_w_Kaczaniwci_Sztenberg.webp",
    title: "Садиба Г. С. Тарновського в Качанівці",
    author: "Василь Штернберг",
    date: "1837 р.",
    style: "Академізм / Романтизм",
    description: "Зразок пейзажного живопису. Відтворює атмосферу дворянської садиби, відомого культурного центру. Пов'язаний із перебуванням Т. Шевченка (дружба митців).",
  },
  {
    id: 9,
    imageUrl: "/images/art/modern/409_Swjatoczne_wororzinnja_Pimonenko.webp",
    title: "Святочне ворожіння",
    author: "Микола Пимоненко",
    date: "1888 р.",
    style: "Етнографічний реалізм",
    description: "Яскравий зразок побутового жанру. Фіксація народних звичаїв (докладне малювання інтер'єру, одягу, обрядовості). Увага до етнографічної точності.",
  },
  {
    id: 10,
    imageUrl: "/images/art/modern/410_Zhnywa_Pimonenko.webp",
    title: "Жнива в Україні",
    author: "Микола Пимоненко",
    date: "1896 р.",
    style: "Реалізм",
    description: "Уславлення праці хліборобів. Увага до героїчного образу трудового народу, що відповідало запитам української інтелігенції.",
  },
  {
    id: 11,
    imageUrl: "/images/art/modern/411_Kozaky_w_stepu_Wasylkiwsky.webp",
    title: "Козаки в степу",
    author: "Сергій Васильківський",
    date: "1890 р.",
    style: "Романтизм",
    description: "Ідеалізація козацької доби («козацька слава»). Ліричний пейзаж як тло для батальної сцени. Звернення до героїчного минулого.",
  },
  {
    id: 12,
    imageUrl: "/images/art/modern/412_Kozaky_piszut_pismo_Repin.webp",
    title: "Запорожці пишуть листа турецькому султанові",
    author: "Ілля Рєпін",
    date: "1880–1891 рр.",
    style: "Реалізм",
    description: "Найвідоміший твір на козацьку тему. Втілення народного гумору, лицарства та внутрішньої єдності козацтва. Яскраві образи, історичний колорит.",
  },
  {
    id: 13,
    imageUrl: "/images/art/modern/413_Portret_Lesi_Ukrainki_Trusz.webp",
    title: "Портрет Лесі Українки",
    author: "Іван Труш",
    date: "1900 р.",
    style: "Реалізм (психологічний портрет)",
    description: "Відтворення інтелектуального та творчого образу видатної поетеси. Передає її сильний характер, аристократичність та глибину.",
  },
  {
    id: 14,
    imageUrl: "/images/art/modern/414_Diwczyna_w_czerwonomu_kapelusi_Muraszko.webp",
    title: "Дівчина в червоному капелюсі",
    author: "Олександр Мурашко",
    date: "1902–1903 рр.",
    style: "Модерн (перехідний етап)",
    description: "Пов'язана з європейським модерном. Яскравий декоративізм, узагальненість форми, сміливе колористичне рішення. Знаковий твір українського модерну.",
  },
  {
    id: 15,
    imageUrl: "/images/art/modern/415_Zhinka_z_kwitamy_Muraszko.webp",
    title: "Жінка з настурціями",
    author: "Олександр Мурашко",
    date: "1918 р.",
    style: "Символізм / Модерн",
    description: "Символічний портрет доби Української революції. Поєднання реалізму з декоративністю. Відображає складну атмосферу початку XX століття.",
  },
  {
    id: 16,
    imageUrl: "/images/art/modern/416_Nareczena_Kriczewsky.webp",
    title: "Наречена",
    author: "Федір Кричевський",
    date: "1910 р.",
    style: "Модерн / Символізм",
    description: "Поєднання стилю модерн з народними традиціями. Декоративна стилізація, увага до українського весільного обряду. Вплив імпресіонізму.",
  },
];