// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMaturalnyApp.Data;

#nullable disable

namespace TestMaturalnyApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628161445_AddTestSessionAndUpdateUserAnswer")]
    partial class AddTestSessionAndUpdateUserAnswer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("MatchLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2545),
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "988 рік"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2547),
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "1054 рік"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2623),
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "1240 рік"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2625),
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "1265 рік"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2626),
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "Київ"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2627),
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Чернігів"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2628),
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Львів"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2629),
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "Переяслав"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2630),
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "монголам"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2631),
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "угорцям"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2632),
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "полякам"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2633),
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "хрестоносцям"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2683),
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "12"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2685),
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "10"
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2686),
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "13"
                        });
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1985),
                            Name = "Історія України"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1993),
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1994),
                            Name = "Інформатика"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1995),
                            Name = "Фізика"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1996),
                            Name = "Англійська мова"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1997),
                            Name = "Українська мова"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(1998),
                            Name = "Польська мова"
                        });
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("float(4)")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2509),
                            MaxScore = 1.0,
                            Text = "Коли відбулося хрещення Русі?",
                            TopicId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2513),
                            MaxScore = 1.0,
                            Text = "Яке місто стало столицею Київської Русі?",
                            TopicId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2514),
                            MaxScore = 2.0,
                            Text = "У 1238 р. під Дорогичином військо князя Данила Галицького завдало поразки?",
                            TopicId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2664),
                            MaxScore = 1.0,
                            Text = "Скільки буде 7 + 5?",
                            TopicId = 100,
                            Type = 0
                        });
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.TestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EndReason")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TestSessions", (string)null);
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2224),
                            Description = "Вступ до історії України.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Вступ до історії України."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2237),
                            Description = "Стародавня історія України.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Стародавня історія України."
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2239),
                            Description = "Русь-Україна (Київська держава).",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Русь-Україна (Київська держава)."
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2240),
                            Description = "Королівство Руське (Галицько-Волинська держава). Монгольська навала.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Королівство Руське (Галицько-Волинська держава). Монгольська навала."
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2241),
                            Description = "Руські удільні князівства у складі іноземних держав у др.п. XIV – п.п. XVI ст. Кримське ханство.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Руські удільні князівства у складі іноземних держав у др.п. XIV – п.п. XVI ст. Кримське ханство."
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2243),
                            Description = "Українські землі у складі Речі Посполитої у др.п. XVI ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Речі Посполитої у др.п. XVI ст."
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2244),
                            Description = "Українські землі у складі Речі Посполитої в п.п. XVII ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Речі Посполитої в п.п. XVII ст."
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2245),
                            Description = "Національно-визвольна війна українського народу середини XVII ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Національно-визвольна війна українського народу середини XVII ст."
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2246),
                            Description = "Козацька Україна наприкінці 50-80-х рр. XVII ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Козацька Україна наприкінці 50-80-х рр. XVII ст."
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2248),
                            Description = "Українські землі наприкінці XVII – в п.п. XVIII ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі наприкінці XVII – в п.п. XVIII ст."
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2249),
                            Description = "Українські землі в др.п. XVIII ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі в др.п. XVIII ст."
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2250),
                            Description = "Українські землі у складі Російської імперії наприкінці XVIII – в п.п. ХІХ ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Російської імперії наприкінці XVIII – в п.п. ХІХ ст."
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2251),
                            Description = "Українські землі у складі Австрійської імперії наприкінці XVIII – в п.п. ХІХ ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Австрійської імперії наприкінці XVIII – в п.п. ХІХ ст."
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2252),
                            Description = "Культура України кінця XVIII – п.п. ХІХ ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Культура України кінця XVIII – п.п. ХІХ ст."
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2252),
                            Description = "Українські землі у складі Російської імперії в др.п ХІХ ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Російської імперії в др.п ХІХ ст."
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2253),
                            Description = "Українські землі у складі Австро-Угорщини в др.п. ХІХ ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Австро-Угорщини в др.п. ХІХ ст."
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2255),
                            Description = "Культура України в др.п. ХІХ – на початку ХХ ст.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Культура України в др.п. ХІХ – на початку ХХ ст."
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2261),
                            Description = "Українські землі у складі Російської імперії в 1900-1914 рр.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Російської імперії в 1900-1914 рр."
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2262),
                            Description = "Українські землі у складі Австро-Угорщини в 1900-1914 рр.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Українські землі у складі Австро-Угорщини в 1900-1914 рр."
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2263),
                            Description = "Україна в роки Першої світової війни.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Україна в роки Першої світової війни."
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2264),
                            Description = "Початок Української революції.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Початок Української революції."
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2265),
                            Description = "Розгортання Української революції.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Розгортання Української революції."
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2266),
                            Description = "Встановлення комуністичного тоталітарного режиму в Україні.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Встановлення комуністичного тоталітарного режиму в Україні."
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2266),
                            Description = "Утвердження більшовицького тоталітарного режиму в Україні.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Утвердження більшовицького тоталітарного режиму в Україні."
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2267),
                            Description = "Західноукраїнські землі в міжвоєнний період.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Західноукраїнські землі в міжвоєнний період."
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2308),
                            Description = "Україна в роки Другої світової війни.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Україна в роки Другої світової війни."
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2310),
                            Description = "Україна в перші повоєнні роки.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Україна в перші повоєнні роки."
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2311),
                            Description = "Україна в умовах десталінізації.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Україна в умовах десталінізації."
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2312),
                            Description = "Україна в період загострення кризи радянської системи.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Україна в період загострення кризи радянської системи."
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2313),
                            Description = "Відновлення незалежності України.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Відновлення незалежності України."
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2314),
                            Description = "Становлення України як незалежної держави.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Становлення України як незалежної держави."
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2315),
                            Description = "Творення нової України.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Творення нової України."
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2316),
                            Description = "Персоналії",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Персоналії"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2318),
                            Description = "Діячі культури освіти і науки.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Діячі культури освіти і науки."
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2318),
                            Description = "Громадсько-політичні та військові діячі.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Громадсько-політичні та військові діячі."
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2319),
                            Description = "Архітектура культових споруд в Україні.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Архітектура культових споруд в Україні."
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2320),
                            Description = "Архітектура фортифікаційних споруд в Україні.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Архітектура фортифікаційних споруд в Україні."
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2321),
                            Description = "Світська архітектура. Містобудування.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Світська архітектура. Містобудування."
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2322),
                            Description = "Скульптура. Пам’ятники.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Скульптура. Пам’ятники."
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2323),
                            Description = "Ікони (Образотворче мистецтво).",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Ікони (Образотворче мистецтво)."
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2324),
                            Description = "Мініатюри. Гравюри. Портрети.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Мініатюри. Гравюри. Портрети."
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2325),
                            Description = "Художні роботи (образотворче мистецтво).",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Художні роботи (образотворче мистецтво)."
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2326),
                            Description = "Пам’ятки стародавньої історії України.",
                            DisciplineId = 1,
                            Level = 0,
                            Title = "Пам’ятки стародавньої історії України."
                        },
                        new
                        {
                            Id = 1000,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2417),
                            Description = "Числа і вирази",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Числа і вирази"
                        },
                        new
                        {
                            Id = 1001,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2421),
                            Description = "Рівняння, нерівності і їх системи",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Рівняння, нерівності і їх системи"
                        },
                        new
                        {
                            Id = 1002,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2422),
                            Description = "Функції",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Функції"
                        },
                        new
                        {
                            Id = 1003,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2423),
                            Description = "Елементи комбінаторики, початки теорії ймовірностей та елементи математичної статистики",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Елементи комбінаторики, початки теорії ймовірностей та елементи математичної статистики"
                        },
                        new
                        {
                            Id = 1004,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2424),
                            Description = "Планіметрія",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Планіметрія"
                        },
                        new
                        {
                            Id = 1005,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2427),
                            Description = "Стереометрія",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Стереометрія"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2460),
                            Description = "Числа і дії з ними",
                            DisciplineId = 2,
                            Level = 0,
                            Title = "Числа і дії з ними"
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2462),
                            Description = "Алгебра",
                            DisciplineId = 2,
                            Level = 0,
                            Title = "Алгебра"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2463),
                            Description = "Геометрія",
                            DisciplineId = 2,
                            Level = 0,
                            Title = "Геометрія"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2464),
                            Description = "Бази даних",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Бази даних"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2465),
                            Description = "Мережі",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Мережі"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2468),
                            Description = "Алгоритми",
                            DisciplineId = 3,
                            Level = 0,
                            Title = "Алгоритми"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2469),
                            Description = "Механіка",
                            DisciplineId = 4,
                            Level = 0,
                            Title = "Механіка"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2470),
                            Description = "Оптика",
                            DisciplineId = 4,
                            Level = 0,
                            Title = "Оптика"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2025, 6, 28, 16, 14, 45, 72, DateTimeKind.Utc).AddTicks(2471),
                            Description = "Електрика",
                            DisciplineId = 4,
                            Level = 0,
                            Title = "Електрика"
                        });
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("float(4)")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("TestSessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserAnswerOption", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerOptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserAnswerId", "AnswerOptionId");

                    b.HasIndex("AnswerOptionId");

                    b.ToTable("UserAnswerOptions");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.AnswerOption", b =>
                {
                    b.HasOne("TestMaturalnyApp.Data.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Question", b =>
                {
                    b.HasOne("TestMaturalnyApp.Data.Entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Topic", b =>
                {
                    b.HasOne("TestMaturalnyApp.Data.Entities.Discipline", "Discipline")
                        .WithMany("Topics")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserAnswer", b =>
                {
                    b.HasOne("TestMaturalnyApp.Data.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestMaturalnyApp.Data.Entities.TestSession", "TestSession")
                        .WithMany("UserAnswers")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestMaturalnyApp.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserAnswerOption", b =>
                {
                    b.HasOne("TestMaturalnyApp.Data.Entities.AnswerOption", "AnswerOption")
                        .WithMany()
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestMaturalnyApp.Data.Entities.UserAnswer", "UserAnswer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("UserAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("UserAnswer");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserToken", b =>
                {
                    b.HasOne("TestMaturalnyApp.Data.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Discipline", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.TestSession", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.Topic", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.User", b =>
                {
                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("TestMaturalnyApp.Data.Entities.UserAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
