// constants/UsefulMaterials/Math/formulasData.ts

// export interface Formula {
//   id: number;
//   section: string;        // Раздел (например, "Алгебра", "Геометрия")
//   sectionIcon: string;    // Иконка раздела
//   title: string;          // Название формулы на украинском
//   formula: string;        // LaTeX формула
//   description?: string;   // Пояснение (опционально)
// }

// export const formulasData: Formula[] = [
//   // === АЛГЕБРА ===
//   {
//     id: 1,
//     section: "Квадратні рівняння",
//     sectionIcon: "📐",
//     title: "Дискримінант квадратного рівняння",
//     formula: "D = b^2 - 4ac",
//     description: "Для рівняння ax² + bx + c = 0",
//   },
//   {
//     id: 2,
//     section: "Квадратні рівняння",
//     sectionIcon: "📐",
//     title: "Корені квадратного рівняння",
//     formula: "x = \\frac{-b \\pm \\sqrt{D}}{2a}",
//     description: "Формула знаходження коренів",
//   },
//   {
//     id: 3,
//     section: "Степені та корені",
//     sectionIcon: "🔢",
//     title: "Властивість степеня",
//     formula: "a^m \\cdot a^n = a^{m+n}",
//   },
//   {
//     id: 4,
//     section: "Степені та корені",
//     sectionIcon: "🔢",
//     title: "Корінь з добутку",
//     formula: "\\sqrt[n]{ab} = \\sqrt[n]{a} \\cdot \\sqrt[n]{b}",
//   },
//   {
//     id: 5,
//     section: "Суми та послідовності",
//     sectionIcon: "🔢",
//     title: "Сума арифметичної прогресії",
//     formula: "S_n = \\frac{a_1 + a_n}{2} \\cdot n",
//   },
//   {
//     id: 6,
//     section: "Суми та послідовності",
//     sectionIcon: "🔢",
//     title: "Сума геометричної прогресії",
//     formula: "S_n = \\frac{b_1(q^n - 1)}{q - 1}",
//   },
//   {
//     id: 7,
//     section: "Логарифми",
//     sectionIcon: "📊",
//     title: "Основна логарифмічна тотожність",
//     formula: "a^{\\log_a b} = b",
//   },
//   {
//     id: 8,
//     section: "Логарифми",
//     sectionIcon: "📊",
//     title: "Логарифм добутку",
//     formula: "\\log_a (bc) = \\log_a b + \\log_a c",
//   },
//   {
//     id: 9,
//     section: "Логарифми",
//     sectionIcon: "📊",
//     title: "Логарифм частки",
//     formula: "\\log_a \\left(\\frac{b}{c}\\right) = \\log_a b - \\log_a c",
//   },
//   {
//     id: 10,
//     section: "Логарифми",
//     sectionIcon: "📊",
//     title: "Логарифм степеня",
//     formula: "\\log_a b^n = n \\log_a b",
//   },
//   {
//     id: 11,
//     section: "Логарифми",
//     sectionIcon: "📊",
//     title: "Перехід до нової основи",
//     formula: "\\log_a b = \\frac{\\log_c b}{\\log_c a}",
//   },
//   {
//     id: 12,
//     section: "Логарифми",
//     sectionIcon: "📊",
//     title: "Особливі випадки",
//     formula: "\\log_a 1 = 0, \\quad \\log_a a = 1",
//   },
//   {
//     id: 13,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Основна тригонометрична тотожність",
//     formula: "\\sin^2 \\alpha + \\cos^2 \\alpha = 1",
//   },
//   {
//     id: 14,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Тангенс через синус і косинус",
//     formula: "\\tan \\alpha = \\frac{\\sin \\alpha}{\\cos \\alpha}",
//   },
//   {
//     id: 15,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Сума кутів (синус)",
//     formula: "\\sin(\\alpha + \\beta) = \\sin \\alpha \\cos \\beta + \\cos \\alpha \\sin \\beta",
//   },
//   {
//     id: 16,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Сума кутів (косинус)",
//     formula: "\\cos(\\alpha + \\beta) = \\cos \\alpha \\cos \\beta - \\sin \\alpha \\sin \\beta",
//   },
//   {
//     id: 17,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Косинус подвійного кута",
//     formula: "\\cos 2\\alpha = \\cos^2 \\alpha - \\sin^2 \\alpha = 2\\cos^2 \\alpha - 1 = 1 - 2\\sin^2 \\alpha",
//   },
//   {
//     id: 18,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Синус подвійного кута",
//     formula: "\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha",
//   },
//   {
//     id: 19,
//     section: "Тригонометрія",
//     sectionIcon: "📐",
//     title: "Обернені тригонометричні функції",
//     formula: "\\arcsin x,\\ \\arccos x,\\ \\arctan x",
//   },

//   // === ГЕОМЕТРІЯ ===
//   {
//     id: 20,
//     section: "Планіметрія",
//     sectionIcon: "📐",
//     title: "Площа квадрата",
//     formula: "S = a^2",
//   },
//   {
//     id: 21,
//     section: "Планіметрія",
//     sectionIcon: "📐",
//     title: "Площа прямокутника",
//     formula: "S = a \\cdot b",
//   },
//   {
//     id: 22,
//     section: "Планіметрія",
//     sectionIcon: "📐",
//     title: "Площа круга",
//     formula: "S = \\pi r^2",
//   },
//   {
//     id: 23,
//     section: "Планіметрія",
//     sectionIcon: "📐",
//     title: "Довжина кола",
//     formula: "C = 2\\pi r = \\pi d",
//   },
//   {
//     id: 24,
//     section: "Теорема Піфагора",
//     sectionIcon: "📐",
//     title: "Теорема Піфагора",
//     formula: "a^2 + b^2 = c^2",
//     description: "для прямокутного трикутника",
//   },

//   // === МАТАНАЛІЗ ===
//   {
//     id: 25,
//     section: "Математичний аналіз",
//     sectionIcon: "∫",
//     title: "Похідна степеневої функції",
//     formula: "(x^n)' = nx^{n-1}",
//   },
//   {
//     id: 26,
//     section: "Математичний аналіз",
//     sectionIcon: "∫",
//     title: "Похідна суми",
//     formula: "(u + v)' = u' + v'",
//   },
//   {
//     id: 27,
//     section: "Математичний аналіз",
//     sectionIcon: "∫",
//     title: "Первісна степеневої функції",
//     formula: "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C,\\ n \\neq -1",
//   },
//   {
//     id: 28,
//     section: "Математичний аналіз",
//     sectionIcon: "∫",
//     title: "Визначений інтеграл",
//     formula: "\\int_{a}^{b} f(x) dx = F(b) - F(a)",
//   },
// ];



// constants/UsefulMaterials/Math/formulasData.ts

export interface Formula {
  id: number;
  section: string;        // Розділ (наприклад, "Алгебра", "Геометрія")
  sectionIcon: string;    // Іконка розділу
  title: string;          // Назва формули українською
  formula: string;        // LaTeX формула
  description?: string;   // Пояснення (опціонально)
}

// ==================== КОНФІГУРАЦІЯ ДЛЯ PDF ====================
export const FORMULAS_COLUMNS = [
  { header: 'Розділ', accessor: (row: Formula) => `${row.sectionIcon || '📐'} ${row.section}`, width: 35 },
  { header: 'Назва формули', accessor: 'title', width: 40 },
  { header: 'Формула', accessor: 'formula', width: 50 },
  { header: 'Опис', accessor: (row: Formula) => row.description || '', width: 'auto' },
] as const;

export const FORMULAS_SHOW_ROW_NUMBERS = false;  // Для формул нумерація не потрібна


export const formulasData: Formula[] = [
  // ==================== 1. РАЦІОНАЛЬНІ ВИРАЗИ. ДІЇ З НИМИ ====================
  {
    id: 1,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Квадрат суми",
    formula: "(a + b)^2 = a^2 + 2ab + b^2",
    description: "Квадрат суми двох виразів",
  },
  {
    id: 2,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Квадрат різниці",
    formula: "(a - b)^2 = a^2 - 2ab + b^2",
    description: "Квадрат різниці двох виразів",
  },
  {
    id: 3,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Різниця квадратів",
    formula: "a^2 - b^2 = (a - b)(a + b)",
  },
  {
    id: 4,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Куб суми",
    formula: "(a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3",
  },
  {
    id: 5,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Куб різниці",
    formula: "(a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3",
  },
  {
    id: 6,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Сума кубів",
    formula: "a^3 + b^3 = (a + b)(a^2 - ab + b^2)",
  },
  {
    id: 7,
    section: "Формули скороченого множення",
    sectionIcon: "✖️",
    title: "Різниця кубів",
    formula: "a^3 - b^3 = (a - b)(a^2 + ab + b^2)",
  },
  {
    id: 8,
    section: "Дії з дробами",
    sectionIcon: "➗",
    title: "Множення дробів",
    formula: "\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{ac}{bd}",
  },
  {
    id: 9,
    section: "Дії з дробами",
    sectionIcon: "➗",
    title: "Ділення дробів",
    formula: "\\frac{a}{b} : \\frac{c}{d} = \\frac{ad}{bc}",
  },
  {
    id: 10,
    section: "Дії з дробами",
    sectionIcon: "➗",
    title: "Додавання дробів",
    formula: "\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}",
  },
  {
    id: 11,
    section: "Дії з дробами",
    sectionIcon: "➗",
    title: "Віднімання дробів",
    formula: "\\frac{a}{b} - \\frac{c}{d} = \\frac{ad - bc}{bd}",
  },

  // ==================== 2. АБСОЛЮТНА ВЕЛИЧИНА ЧИСЛА. МОДУЛІ ====================
  {
    id: 12,
    section: "Модуль числа",
    sectionIcon: "⎮",
    title: "Означення модуля",
    formula: "|a| = \\begin{cases} a, & a \\ge 0 \\\\ -a, & a < 0 \\end{cases}",
  },
  {
    id: 13,
    section: "Модуль числа",
    sectionIcon: "⎮",
    title: "Модуль добутку",
    formula: "|a \\cdot b| = |a| \\cdot |b|",
  },
  {
    id: 14,
    section: "Модуль числа",
    sectionIcon: "⎮",
    title: "Модуль частки",
    formula: "\\left|\\frac{a}{b}\\right| = \\frac{|a|}{|b|}, \\quad b \\neq 0",
  },
  {
    id: 15,
    section: "Модуль числа",
    sectionIcon: "⎮",
    title: "Нерівність трикутника",
    formula: "|a + b| \\le |a| + |b|",
  },
  {
    id: 16,
    section: "Модуль числа",
    sectionIcon: "⎮",
    title: "Квадратний корінь квадрата",
    formula: "\\sqrt{a^2} = |a|",
  },

  // ==================== 3. КВАДРАТНІ РІВНЯННЯ ====================
  {
    id: 17,
    section: "Квадратні рівняння",
    sectionIcon: "📐",
    title: "Загальний вигляд",
    formula: "ax^2 + bx + c = 0, \\quad a \\neq 0",
  },
  {
    id: 18,
    section: "Квадратні рівняння",
    sectionIcon: "📐",
    title: "Дискримінант",
    formula: "D = b^2 - 4ac",
  },
  {
    id: 19,
    section: "Квадратні рівняння",
    sectionIcon: "📐",
    title: "Корені (D > 0)",
    formula: "x_{1,2} = \\frac{-b \\pm \\sqrt{D}}{2a}",
  },
  {
    id: 20,
    section: "Квадратні рівняння",
    sectionIcon: "📐",
    title: "Корені (D = 0)",
    formula: "x = -\\frac{b}{2a}",
  },
  {
    id: 21,
    section: "Квадратні рівняння",
    sectionIcon: "📐",
    title: "Теорема Вієта",
    formula: "x_1 + x_2 = -\\frac{b}{a},\\quad x_1 \\cdot x_2 = \\frac{c}{a}",
  },
  {
    id: 22,
    section: "Квадратні рівняння",
    sectionIcon: "📐",
    title: "Розкладання на множники",
    formula: "ax^2 + bx + c = a(x - x_1)(x - x_2)",
  },

  // ==================== 4. СТЕПЕНІ, ЛОГАРИФМИ, ПОКАЗНИКОВІ ФУНКЦІЇ ====================
  {
    id: 23,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Степінь з натуральним показником",
    formula: "a^n = \\underbrace{a \\cdot a \\cdot \\ldots \\cdot a}_{n \\text{ разів}}",
  },
  {
    id: 24,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Нульовий степінь",
    formula: "a^0 = 1, \\quad a \\neq 0",
  },
  {
    id: 25,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Від'ємний степінь",
    formula: "a^{-n} = \\frac{1}{a^n}, \\quad a \\neq 0",
  },
  {
    id: 26,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Дробовий степінь",
    formula: "a^{\\frac{m}{n}} = \\sqrt[n]{a^m}, \\quad a > 0",
  },
  {
    id: 27,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Множення степенів",
    formula: "a^m \\cdot a^n = a^{m+n}",
  },
  {
    id: 28,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Ділення степенів",
    formula: "\\frac{a^m}{a^n} = a^{m-n}",
  },
  {
    id: 29,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Степінь степеня",
    formula: "(a^m)^n = a^{m \\cdot n}",
  },
  {
    id: 30,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Степінь добутку",
    formula: "(ab)^n = a^n \\cdot b^n",
  },
  {
    id: 31,
    section: "Степені",
    sectionIcon: "🔢",
    title: "Степінь частки",
    formula: "\\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}",
  },
  {
    id: 32,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Основна логарифмічна тотожність",
    formula: "a^{\\log_a b} = b, \\quad a > 0, a \\neq 1, b > 0",
  },
  {
    id: 33,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Логарифм одиниці",
    formula: "\\log_a 1 = 0",
  },
  {
    id: 34,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Логарифм основи",
    formula: "\\log_a a = 1",
  },
  {
    id: 35,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Логарифм добутку",
    formula: "\\log_a(b \\cdot c) = \\log_a b + \\log_a c",
  },
  {
    id: 36,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Логарифм частки",
    formula: "\\log_a \\frac{b}{c} = \\log_a b - \\log_a c",
  },
  {
    id: 37,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Логарифм степеня",
    formula: "\\log_a b^n = n \\cdot \\log_a b",
  },
  {
    id: 38,
    section: "Логарифми",
    sectionIcon: "📊",
    title: "Перехід до іншої основи",
    formula: "\\log_a b = \\frac{\\log_c b}{\\log_c a}",
  },
  {
    id: 39,
    section: "Показникові рівняння",
    sectionIcon: "📈",
    title: "Найпростіше показникове рівняння",
    formula: "a^{f(x)} = a^{g(x)} \\Rightarrow f(x) = g(x), \\quad a > 0, a \\neq 1",
  },
  {
    id: 40,
    section: "Логарифмічні рівняння",
    sectionIcon: "📉",
    title: "Найпростіше логарифмічне рівняння",
    formula: "\\log_a f(x) = \\log_a g(x) \\Rightarrow f(x) = g(x), \\quad f(x) > 0, g(x) > 0",
  },

  // ==================== 5. АРИФМЕТИЧНА ТА ГЕОМЕТРИЧНА ПРОГРЕСІЇ ====================
  {
    id: 41,
    section: "Арифметична прогресія",
    sectionIcon: "🔢",
    title: "n-й член",
    formula: "a_n = a_1 + (n-1)d",
  },
  {
    id: 42,
    section: "Арифметична прогресія",
    sectionIcon: "🔢",
    title: "Сума n перших членів",
    formula: "S_n = \\frac{a_1 + a_n}{2} \\cdot n = \\frac{2a_1 + (n-1)d}{2} \\cdot n",
  },
  {
    id: 43,
    section: "Геометрична прогресія",
    sectionIcon: "🔢",
    title: "n-й член",
    formula: "b_n = b_1 \\cdot q^{n-1}",
  },
  {
    id: 44,
    section: "Геометрична прогресія",
    sectionIcon: "🔢",
    title: "Сума n перших членів (q ≠ 1)",
    formula: "S_n = \\frac{b_1(q^n - 1)}{q - 1} = \\frac{b_1(1 - q^n)}{1 - q}",
  },
  {
    id: 45,
    section: "Геометрична прогресія",
    sectionIcon: "🔢",
    title: "Сума нескінченної спадної прогресії",
    formula: "S = \\frac{b_1}{1 - q}, \\quad |q| < 1",
  },

  // ==================== 6. ТРИГОНОМЕТРІЯ ====================
  {
    id: 46,
    section: "Основні тригонометричні тотожності",
    sectionIcon: "📐",
    title: "Основна тотожність",
    formula: "\\sin^2 \\alpha + \\cos^2 \\alpha = 1",
  },
  {
    id: 47,
    section: "Основні тригонометричні тотожності",
    sectionIcon: "📐",
    title: "Тангенс через синус і косинус",
    formula: "\\tg \\alpha = \\frac{\\sin \\alpha}{\\cos \\alpha}",
  },
  {
    id: 48,
    section: "Основні тригонометричні тотожності",
    sectionIcon: "📐",
    title: "Котангенс",
    formula: "\\ctg \\alpha = \\frac{\\cos \\alpha}{\\sin \\alpha} = \\frac{1}{\\tg \\alpha}",
  },
  {
    id: 49,
    section: "Основні тригонометричні тотожності",
    sectionIcon: "📐",
    title: "Тангенс і косинус",
    formula: "1 + \\tg^2 \\alpha = \\frac{1}{\\cos^2 \\alpha}",
  },
  {
    id: 50,
    section: "Основні тригонометричні тотожності",
    sectionIcon: "📐",
    title: "Котангенс і синус",
    formula: "1 + \\ctg^2 \\alpha = \\frac{1}{\\sin^2 \\alpha}",
  },
  {
    id: 51,
    section: "Формули подвійного кута",
    sectionIcon: "📐",
    title: "Синус подвійного кута",
    formula: "\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha",
  },
  {
    id: 52,
    section: "Формули подвійного кута",
    sectionIcon: "📐",
    title: "Косинус подвійного кута",
    formula: "\\cos 2\\alpha = \\cos^2 \\alpha - \\sin^2 \\alpha = 2\\cos^2 \\alpha - 1 = 1 - 2\\sin^2 \\alpha",
  },
  {
    id: 53,
    section: "Формули подвійного кута",
    sectionIcon: "📐",
    title: "Тангенс подвійного кута",
    formula: "\\tg 2\\alpha = \\frac{2\\tg \\alpha}{1 - \\tg^2 \\alpha}",
  },
  {
    id: 54,
    section: "Формули суми кутів",
    sectionIcon: "📐",
    title: "Синус суми",
    formula: "\\sin(\\alpha + \\beta) = \\sin \\alpha \\cos \\beta + \\cos \\alpha \\sin \\beta",
  },
  {
    id: 55,
    section: "Формули суми кутів",
    sectionIcon: "📐",
    title: "Синус різниці",
    formula: "\\sin(\\alpha - \\beta) = \\sin \\alpha \\cos \\beta - \\cos \\alpha \\sin \\beta",
  },
  {
    id: 56,
    section: "Формули суми кутів",
    sectionIcon: "📐",
    title: "Косинус суми",
    formula: "\\cos(\\alpha + \\beta) = \\cos \\alpha \\cos \\beta - \\sin \\alpha \\sin \\beta",
  },
  {
    id: 57,
    section: "Формули суми кутів",
    sectionIcon: "📐",
    title: "Косинус різниці",
    formula: "\\cos(\\alpha - \\beta) = \\cos \\alpha \\cos \\beta + \\sin \\alpha \\sin \\beta",
  },
  {
    id: 58,
    section: "Формули зведення",
    sectionIcon: "🔄",
    title: "Синус (90° - α)",
    formula: "\\sin(90^\\circ - \\alpha) = \\cos \\alpha",
  },
  {
    id: 59,
    section: "Формули зведення",
    sectionIcon: "🔄",
    title: "Косинус (90° - α)",
    formula: "\\cos(90^\\circ - \\alpha) = \\sin \\alpha",
  },
  {
    id: 60,
    section: "Формули зведення",
    sectionIcon: "🔄",
    title: "Синус (90° + α)",
    formula: "\\sin(90^\\circ + \\alpha) = \\cos \\alpha",
  },
  {
    id: 61,
    section: "Формули зведення",
    sectionIcon: "🔄",
    title: "Косинус (90° + α)",
    formula: "\\cos(90^\\circ + \\alpha) = -\\sin \\alpha",
  },
  {
    id: 62,
    section: "Формули зведення",
    sectionIcon: "🔄",
    title: "Синус (180° - α)",
    formula: "\\sin(180^\\circ - \\alpha) = \\sin \\alpha",
  },
  {
    id: 63,
    section: "Формули зведення",
    sectionIcon: "🔄",
    title: "Косинус (180° - α)",
    formula: "\\cos(180^\\circ - \\alpha) = -\\cos \\alpha",
  },
  {
    id: 64,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "sin 0°",
    formula: "\\sin 0^\\circ = 0",
  },
  {
    id: 65,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "sin 30°",
    formula: "\\sin 30^\\circ = \\frac{1}{2}",
  },
  {
    id: 66,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "sin 45°",
    formula: "\\sin 45^\\circ = \\frac{\\sqrt{2}}{2}",
  },
  {
    id: 67,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "sin 60°",
    formula: "\\sin 60^\\circ = \\frac{\\sqrt{3}}{2}",
  },
  {
    id: 68,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "sin 90°",
    formula: "\\sin 90^\\circ = 1",
  },
  {
    id: 69,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "cos 0°",
    formula: "\\cos 0^\\circ = 1",
  },
  {
    id: 70,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "cos 30°",
    formula: "\\cos 30^\\circ = \\frac{\\sqrt{3}}{2}",
  },
  {
    id: 71,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "cos 45°",
    formula: "\\cos 45^\\circ = \\frac{\\sqrt{2}}{2}",
  },
  {
    id: 72,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "cos 60°",
    formula: "\\cos 60^\\circ = \\frac{1}{2}",
  },
  {
    id: 73,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "cos 90°",
    formula: "\\cos 90^\\circ = 0",
  },
  {
    id: 74,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "tg 0°",
    formula: "\\tg 0^\\circ = 0",
  },
  {
    id: 75,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "tg 30°",
    formula: "\\tg 30^\\circ = \\frac{1}{\\sqrt{3}}",
  },
  {
    id: 76,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "tg 45°",
    formula: "\\tg 45^\\circ = 1",
  },
  {
    id: 77,
    section: "Таблиця значень",
    sectionIcon: "📊",
    title: "tg 60°",
    formula: "\\tg 60^\\circ = \\sqrt{3}",
  },

  // ==================== 7. ТЕОРІЯ ЙМОВІРНОСТЕЙ ТА КОМБІНАТОРИКА ====================
  {
    id: 78,
    section: "Комбінаторика",
    sectionIcon: "🎲",
    title: "Факторіал",
    formula: "n! = 1 \\cdot 2 \\cdot 3 \\cdot \\ldots \\cdot n",
  },
  {
    id: 79,
    section: "Комбінаторика",
    sectionIcon: "🎲",
    title: "Перестановки (P_n)",
    formula: "P_n = n!",
  },
  {
    id: 80,
    section: "Комбінаторика",
    sectionIcon: "🎲",
    title: "Розміщення (A_n^k)",
    formula: "A_n^k = \\frac{n!}{(n-k)!}",
  },
  {
    id: 81,
    section: "Комбінаторика",
    sectionIcon: "🎲",
    title: "Комбінації (C_n^k)",
    formula: "C_n^k = \\frac{n!}{k!(n-k)!}",
  },
  {
    id: 82,
    section: "Теорія ймовірностей",
    sectionIcon: "🎲",
    title: "Класичне означення ймовірності",
    formula: "P(A) = \\frac{m}{n}",
    description: "m — кількість сприятливих подій, n — загальна кількість подій",
  },

  // ==================== 8. МАТЕМАТИЧНИЙ АНАЛІЗ ====================
  {
    id: 83,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна сталої",
    formula: "(C)' = 0",
  },
  {
    id: 84,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна степеневої функції",
    formula: "(x^n)' = nx^{n-1}",
  },
  {
    id: 85,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна кореня",
    formula: "(\\sqrt{x})' = \\frac{1}{2\\sqrt{x}}",
  },
  {
    id: 86,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна експоненти",
    formula: "(e^x)' = e^x",
  },
  {
    id: 87,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна натурального логарифма",
    formula: "(\\ln x)' = \\frac{1}{x}",
  },
  {
    id: 88,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна синуса",
    formula: "(\\sin x)' = \\cos x",
  },
  {
    id: 89,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна косинуса",
    formula: "(\\cos x)' = -\\sin x",
  },
  {
    id: 90,
    section: "Похідна",
    sectionIcon: "∫",
    title: "Похідна тангенса",
    formula: "(\\tg x)' = \\frac{1}{\\cos^2 x}",
  },
  {
    id: 91,
    section: "Правила диференціювання",
    sectionIcon: "∫",
    title: "Похідна суми",
    formula: "(u + v)' = u' + v'",
  },
  {
    id: 92,
    section: "Правила диференціювання",
    sectionIcon: "∫",
    title: "Похідна добутку",
    formula: "(uv)' = u'v + uv'",
  },
  {
    id: 93,
    section: "Правила диференціювання",
    sectionIcon: "∫",
    title: "Похідна частки",
    formula: "\\left(\\frac{u}{v}\\right)' = \\frac{u'v - uv'}{v^2}",
  },
  {
    id: 94,
    section: "Первісна",
    sectionIcon: "∫",
    title: "Первісна сталої",
    formula: "\\int C \\, dx = Cx + C_1",
  },
  {
    id: 95,
    section: "Первісна",
    sectionIcon: "∫",
    title: "Первісна степеневої функції",
    formula: "\\int x^n \\, dx = \\frac{x^{n+1}}{n+1} + C, \\quad n \\neq -1",
  },
  {
    id: 96,
    section: "Первісна",
    sectionIcon: "∫",
    title: "Первісна 1/x",
    formula: "\\int \\frac{1}{x} \\, dx = \\ln |x| + C",
  },
  {
    id: 97,
    section: "Первісна",
    sectionIcon: "∫",
    title: "Первісна експоненти",
    formula: "\\int e^x \\, dx = e^x + C",
  },
  {
    id: 98,
    section: "Первісна",
    sectionIcon: "∫",
    title: "Первісна синуса",
    formula: "\\int \\sin x \\, dx = -\\cos x + C",
  },
  {
    id: 99,
    section: "Первісна",
    sectionIcon: "∫",
    title: "Первісна косинуса",
    formula: "\\int \\cos x \\, dx = \\sin x + C",
  },
  {
    id: 100,
    section: "Визначений інтеграл",
    sectionIcon: "∫",
    title: "Формула Ньютона-Лейбніца",
    formula: "\\int_a^b f(x) \\, dx = F(b) - F(a)",
    description: "де F(x) — первісна для f(x)",
  },

  // ==================== 9. ПЛАНІМЕТРІЯ ====================
  {
    id: 101,
    section: "Трикутники",
    sectionIcon: "📐",
    title: "Сума кутів трикутника",
    formula: "\\alpha + \\beta + \\gamma = 180^\\circ",
  },
  {
    id: 102,
    section: "Трикутники",
    sectionIcon: "📐",
    title: "Площа трикутника (через сторону і висоту)",
    formula: "S = \\frac{1}{2} a \\cdot h_a",
  },
  {
    id: 103,
    section: "Трикутники",
    sectionIcon: "📐",
    title: "Площа трикутника (через дві сторони і кут)",
    formula: "S = \\frac{1}{2} ab \\cdot \\sin \\alpha",
  },
  {
    id: 104,
    section: "Трикутники",
    sectionIcon: "📐",
    title: "Площа трикутника (Формула Герона)",
    formula: "S = \\sqrt{p(p-a)(p-b)(p-c)}",
    description: "де p = (a+b+c)/2 — півпериметр",
  },
  {
    id: 105,
    section: "Трикутники",
    sectionIcon: "📐",
    title: "Теорема синусів",
    formula: "\\frac{a}{\\sin \\alpha} = \\frac{b}{\\sin \\beta} = \\frac{c}{\\sin \\gamma} = 2R",
  },
  {
    id: 106,
    section: "Трикутники",
    sectionIcon: "📐",
    title: "Теорема косинусів",
    formula: "a^2 = b^2 + c^2 - 2bc \\cdot \\cos \\alpha",
  },
  {
    id: 107,
    section: "Прямокутний трикутник",
    sectionIcon: "📐",
    title: "Теорема Піфагора",
    formula: "a^2 + b^2 = c^2",
  },
  {
  id: 108,
  section: "Прямокутний трикутник",
  sectionIcon: "📐",
  title: "Синус гострого кута",
  formula: "\\sin \\alpha = \\frac{a}{c}",
  description: "де a — протилежний катет, c — гіпотенуза",
  },
  {
    id: 109,
    section: "Прямокутний трикутник",
    sectionIcon: "📐",
    title: "Косинус гострого кута",
    formula: "\\cos \\alpha = \\frac{b}{c}",
    description: "де b — прилеглий катет, c — гіпотенуза",
  },
  {
    id: 110,
    section: "Прямокутний трикутник",
    sectionIcon: "📐",
    title: "Тангенс гострого кута",
    formula: "\\tg \\alpha = \\frac{a}{b}",
    description: "де a — протилежний катет, b — прилеглий катет",
  },
  {
    id: 111,
    section: "Чотирикутники",
    sectionIcon: "⬛",
    title: "Площа прямокутника",
    formula: "S = a \\cdot b",
  },
  {
    id: 112,
    section: "Чотирикутники",
    sectionIcon: "⬛",
    title: "Площа квадрата",
    formula: "S = a^2",
  },
  {
    id: 113,
    section: "Чотирикутники",
    sectionIcon: "⬛",
    title: "Площа паралелограма",
    formula: "S = a \\cdot h_a = ab \\cdot \\sin \\alpha",
  },
  {
    id: 114,
    section: "Чотирикутники",
    sectionIcon: "⬛",
    title: "Площа ромба",
    formula: "S = \\frac{d_1 \\cdot d_2}{2} = a^2 \\sin \\alpha",
  },
  {
    id: 115,
    section: "Чотирикутники",
    sectionIcon: "⬛",
    title: "Площа трапеції",
    formula: "S = \\frac{a + b}{2} \\cdot h",
  },
  {
    id: 116,
    section: "Коло",
    sectionIcon: "○",
    title: "Довжина кола",
    formula: "L = 2\\pi R = \\pi D",
  },
  {
    id: 117,
    section: "Коло",
    sectionIcon: "○",
    title: "Площа круга",
    formula: "S = \\pi R^2",
  },

    // ==================== 10. СТЕРЕОМЕТРІЯ ====================
  {
  id: 118,
  section: "Призма",
  sectionIcon: "📦",
  title: "Об'єм прямої призми",
  formula: "V = S_{base} \\cdot h",
  description: "S_base — площа основи, h — висота",
  },
  {
    id: 119,
    section: "Призма",
    sectionIcon: "📦",
    title: "Площа бічної поверхні прямої призми",
    formula: "S_{lat} = P_{base} \\cdot h",
    description: "P_base — периметр основи, h — висота",
  },
  {
    id: 120,
    section: "Призма",
    sectionIcon: "📦",
    title: "Площа повної поверхні призми",
    formula: "S_{total} = S_{lat} + 2S_{base}",
  },
  {
    id: 121,
    section: "Піраміда",
    sectionIcon: "🔺",
    title: "Об'єм піраміди",
    formula: "V = \\frac{1}{3} S_{base} \\cdot h",
  },
  {
    id: 122,
    section: "Піраміда",
    sectionIcon: "🔺",
    title: "Площа бічної поверхні правильної піраміди",
    formula: "S_{lat} = \\frac{1}{2} P_{base} \\cdot l",
    description: "l — апофема",
  },
  {
    id: 123,
    section: "Піраміда",
    sectionIcon: "🔺",
    title: "Площа повної поверхні піраміди",
    formula: "S_{total} = S_{lat} + S_{base}",
  },
  {
    id: 124,
    section: "Циліндр",
    sectionIcon: "🧴",
    title: "Об'єм циліндра",
    formula: "V = \\pi R^2 h",
  },
  {
    id: 125,
    section: "Циліндр",
    sectionIcon: "🧴",
    title: "Площа бічної поверхні циліндра",
    formula: "S_{lat} = 2\\pi R h",
  },
  {
    id: 126,
    section: "Циліндр",
    sectionIcon: "🧴",
    title: "Площа повної поверхні циліндра",
    formula: "S_{total} = 2\\pi R (R + h)",
  },
  {
    id: 127,
    section: "Конус",
    sectionIcon: "🎩",
    title: "Об'єм конуса",
    formula: "V = \\frac{1}{3} \\pi R^2 h",
  },
  {
    id: 128,
    section: "Конус",
    sectionIcon: "🎩",
    title: "Площа бічної поверхні конуса",
    formula: "S_{lat} = \\pi R l",
    description: "l — твірна конуса",
  },
  {
    id: 129,
    section: "Конус",
    sectionIcon: "🎩",
    title: "Площа повної поверхні конуса",
    formula: "S_{total} = \\pi R (R + l)",
  },
  {
    id: 130,
    section: "Сфера та куля",
    sectionIcon: "⚽",
    title: "Об'єм кулі",
    formula: "V = \\frac{4}{3} \\pi R^3",
  },
  {
    id: 131,
    section: "Сфера та куля",
    sectionIcon: "⚽",
    title: "Площа поверхні сфери",
    formula: "S = 4\\pi R^2",
  },

  // ==================== 11. КООРДИНАТИ ТА ВЕКТОРИ ====================
  {
    id: 132,
    section: "Координати на площині",
    sectionIcon: "📍",
    title: "Відстань між двома точками",
    formula: "d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}",
  },
  {
    id: 133,
    section: "Координати на площині",
    sectionIcon: "📍",
    title: "Координати середини відрізка",
    formula: "x = \\frac{x_1 + x_2}{2},\\quad y = \\frac{y_1 + y_2}{2}",
  },
  {
    id: 134,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Координати вектора",
    formula: "\\vec{AB} = (x_2 - x_1,\\ y_2 - y_1)",
  },
  {
    id: 135,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Довжина вектора",
    formula: "|\\vec{a}| = \\sqrt{a_x^2 + a_y^2}",
  },
  {
    id: 136,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Скалярний добуток векторів",
    formula: "\\vec{a} \\cdot \\vec{b} = a_x b_x + a_y b_y = |\\vec{a}| \\cdot |\\vec{b}| \\cdot \\cos \\varphi",
  },
  {
    id: 137,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Кут між векторами",
    formula: "\\cos \\varphi = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{a}| \\cdot |\\vec{b}|}",
  },
  {
    id: 138,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Умова перпендикулярності векторів",
    formula: "\\vec{a} \\perp \\vec{b} \\Leftrightarrow \\vec{a} \\cdot \\vec{b} = 0",
  },
  {
    id: 139,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Умова колінеарності векторів",
    formula: "\\vec{a} \\parallel \\vec{b} \\Leftrightarrow \\frac{a_x}{b_x} = \\frac{a_y}{b_y}",
  },
  {
    id: 140,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Координати у просторі (відстань)",
    formula: "d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}",
  },
  {
    id: 141,
    section: "Вектори",
    sectionIcon: "➡️",
    title: "Скалярний добуток у просторі",
    formula: "\\vec{a} \\cdot \\vec{b} = a_x b_x + a_y b_y + a_z b_z",
  },

  // ==================== 12. ЕЛЕМЕНТИ МАТЕМАТИЧНОЇ СТАТИСТИКИ ====================
  {
    id: 142,
    section: "Статистика",
    sectionIcon: "📊",
    title: "Середнє арифметичне",
    formula: "\\bar{x} = \\frac{x_1 + x_2 + \\ldots + x_n}{n}",
  },
  {
    id: 143,
    section: "Статистика",
    sectionIcon: "📊",
    title: "Медіана (непарна кількість)",
    formula: "Me = x_{\\frac{n+1}{2}}",
    description: "Серединне значення впорядкованого ряду",
  },
  {
    id: 144,
    section: "Статистика",
    sectionIcon: "📊",
    title: "Медіана (парна кількість)",
    formula: "Me = \\frac{x_{\\frac{n}{2}} + x_{\\frac{n}{2}+1}}{2}",
  },
  {
    id: 145,
    section: "Статистика",
    sectionIcon: "📊",
    title: "Мода",
    formula: "Mo = \\text{найчастіше значення}",
  },
  {
    id: 146,
    section: "Статистика",
    sectionIcon: "📊",
    title: "Дисперсія",
    formula: "\\sigma^2 = \\frac{\\sum_{i=1}^{n} (x_i - \\bar{x})^2}{n}",
  },
  {
    id: 147,
    section: "Статистика",
    sectionIcon: "📊",
    title: "Середнє квадратичне відхилення",
    formula: "\\sigma = \\sqrt{\\sigma^2}",
  },

  // ==================== 13. ДОДАТКОВІ ФОРМУЛИ ТА ВЛАСТИВОСТІ ====================
  {
    id: 148,
    section: "Нерівності",
    sectionIcon: "⚖️",
    title: "Властивість модуля (нерівність трикутника)",
    formula: "|a + b| \\le |a| + |b|",
  },
  {
    id: 149,
    section: "Нерівності",
    sectionIcon: "⚖️",
    title: "Нерівність Коші-Буняковського",
    formula: "(a_1^2 + a_2^2)(b_1^2 + b_2^2) \\ge (a_1 b_1 + a_2 b_2)^2",
  },
  {
    id: 150,
    section: "Прогресії",
    sectionIcon: "🔢",
    title: "Середнє арифметичне трьох членів арифм. прогресії",
    formula: "a_n = \\frac{a_{n-1} + a_{n+1}}{2}",
  },
  {
    id: 151,
    section: "Прогресії",
    sectionIcon: "🔢",
    title: "Середнє геометричне трьох членів геом. прогресії",
    formula: "b_n = \\sqrt{b_{n-1} \\cdot b_{n+1}}",
  },
];

// Кількість формул у кожному розділі для перевірки
export const formulasStats = {
  "Формули скороченого множення": 7,
  "Дії з дробами": 4,
  "Модуль числа": 5,
  "Квадратні рівняння": 6,
  "Степені": 9,
  "Логарифми": 8,
  "Показникові рівняння": 1,
  "Логарифмічні рівняння": 1,
  "Арифметична прогресія": 2,
  "Геометрична прогресія": 3,
  "Основні тригонометричні тотожності": 5,
  "Формули подвійного кута": 3,
  "Формули суми кутів": 4,
  "Формули зведення": 6,
  "Таблиця значень": 14,
  "Комбінаторика": 4,
  "Теорія ймовірностей": 1,
  "Похідна": 9,
  "Правила диференціювання": 3,
  "Первісна": 6,
  "Визначений інтеграл": 1,
  "Трикутники": 7,
  "Прямокутний трикутник": 4,
  "Чотирикутники": 5,
  "Коло": 2,
  "Призма": 3,
  "Піраміда": 3,
  "Циліндр": 3,
  "Конус": 3,
  "Сфера та куля": 2,
  "Координати на площині": 2,
  "Вектори": 7,
  "Статистика": 6,
  "Нерівності": 2,
  "Прогресії": 2,
};

// Всього формул: 151